export default defineEventHandler((event) => {
  return [
    { id: 0, name: "HTML5", level: 100 },
    { id: 1, name: "CSS3/SCSS", level: 100 },
    { id: 2, name: "JavaScript", level: 100 },
    { id: 3, name: "TypeScript", level: 100 },
    { id: 4, name: "Vue 2.0, Vue 3.0", level: 100 },
    { id: 5, name: "PHP", level: 100 },
    { id: 6, name: "Laravel", level: 100 },
    { id: 7, name: "Python", level: 100 },
    { id: 8, name: "Django", level: 100 },
    { id: 9, name: "Flask", level: 100 },
    { id: 10, name: "PostgreSQL", level: 100 },
    { id: 11, name: "MySQL", level: 100 },
    { id: 12, name: "MongoDB", level: 100 },
    { id: 13, name: "Redis", level: 100 },
    { id: 14, name: "Docker/Docker Compose", level: 100 },
    { id: 15, name: "RabbitMQ", level: 100 },
    { id: 16, name: "REST APIs", level: 100 },
    { id: 17, name: "GraphQL", level: 100 },
    { id: 18, name: "Git", level: 100 },
    { id: 19, name: "CI/CD", level: 100 },
    { id: 20, name: "OWASP", level: 100 },
    { id: 21, name: "Agile/Scrum", level: 100 },
    { id: 22, name: "Linux", level: 100 },
    { id: 23, name: "Bash Scripting", level: 100 },
  ];
});
